name: AI_env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.11.11=h9e4cc4f_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - accuracy==0.1.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - astunparse==1.6.3
      - attrs==25.4.0
      - blis==1.3.0
      - catalogue==2.0.10
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpathlib==0.23.0
      - clumper==0.2.15
      - confection==0.1.5
      - contourpy==1.3.3
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==4.2.0
      - deepspeed==0.18.0
      - dill==0.4.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - evaluate==0.4.6
      - filelock==3.20.0
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - keras==3.11.3
      - kiwisolver==1.4.9
      - langcodes==3.5.0
      - language-data==1.3.0
      - libclang==18.1.1
      - llvmlite==0.45.1
      - marisa-trie==1.3.1
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - modelscope==1.31.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - namex==0.1.0
      - narwhals==2.7.0
      - networkx==3.5
      - ninja==1.13.0
      - nltk==3.9.2
      - numba==0.62.1
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.17.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - preshed==3.0.10
      - propcache==0.4.1
      - protobuf==6.32.1
      - psutil==7.1.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-learn==1.5.2
      - scipy==1.16.2
      - seaborn==0.13.2
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.3.1
      - sniffio==1.3.1
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - tf-keras==2.20.1
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.57.0
      - triton==3.4.0
      - typer==0.19.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: ~/anaconda3/envs/AI_env
